Hotfix/desktop close menu
finnishtransportagency/ratatiedot-extranet pull request #128
Opened 2023-01-04 12:51 UTC by NinaDang97

- Closing menu on desktop will collapse nested menu items

Ugly gap before:
![Screenshot 2023-01-04 at 14 49 58](https://user-images.githubusercontent.com/31354481/210558712-1daf7d88-06a2-47e6-8d84-0ced35284bf7.png)

2023-01-04 13:18 UTC, mehtis approved these changes

2023-01-04 13:24 UTC, mehtis requested changes
When trying to clear search field when the recent searches is open. It doesn't do that before that has disappeared. Same for the filters-button.

2023-01-04 14:40 UTC, saneDG requested changes
Created PR that points to this branch. Check it out if it fixes issue. 
https://github.com/finnishtransportagency/ratatiedot-extranet/pull/129

2023-01-05 06:02 UTC, mehtis commented
Latest searches seems to be working fine now! Should this also be added to filters as well? Just a thought.

2023-01-05 06:02 UTC, mehtis approved these changes

2023-01-05 07:11 UTC, merged