Feat/RTENU-183 delete file
finnishtransportagency/ratatiedot-extranet pull request #185
Opened 2023-03-15 15:01 UTC by saneDG

User can select file from list. Selected item has blue background color.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/34033265/225872277-c8ca00a9-71d5-4a18-a72d-708688c5b9e5.png">

User can see selected file in modal before request is invoked. User can cancel or delete selected file.
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/34033265/225872561-7ecc7a52-095a-4c51-b7c1-3fcc274df4de.png">

Deleted file is removed from the file list.

This is supposed to work as minimum implementation of file delete feature. UI **will** be fixed in the future.

- New components: [FileDeleteDialog.tsx](https://github.com/finnishtransportagency/ratatiedot-extranet/compare/feat/RTENU-183-delete-file?expand=1#diff-c4ac3fdb2209d0dac0a447d5ce50c273d16c7bfef6c989242be4db3dcbebaa2d), [FileDeleteDialogButton.tsx](https://github.com/finnishtransportagency/ratatiedot-extranet/compare/feat/RTENU-183-delete-file?expand=1#diff-aadd9d2e8ed017c9d9fc7bda014250e4f12c18fb92d7155271c42ff760a933ee)
- 
- New functions
  - deleteFile: Delete sigle file

2023-03-16 05:04 UTC, NinaDang97 requested changes
Overall LGTM! But same question: could we delete file and the file list updates new change (e.g. by removing the successfully deleted file)? Currently, the file list remains the same after I deleted one file

2023-03-17 10:00 UTC, saneDG commented
Updated PR:
- Allow deleting only one file at once
- Update list after file has been deleted
- Update translations. Necessary due to the changes mentioned above.

2023-03-17 10:02 UTC, saneDG commented
Selected item background color might be too subtle to even see in some monitors. I would like do some changes to that later.

2023-03-17 10:04 UTC, NinaDang97 commented on packages/frontend/src/components/Files/CategoryFiles.tsx
> +    // find index of node and remove it from array
deleteFile? :D

2023-03-17 10:23 UTC, NinaDang97 commented on packages/frontend/src/components/Files/CategoryFiles.tsx
> +      newList.splice(index, 1);
Or instead can use `fileList.slice(index, 1)` so we won't need `newList`?

2023-03-17 10:25 UTC, NinaDang97 commented on packages/frontend/src/components/Files/CategoryFiles.tsx
> +      newList.splice(index, 1);
And `totalFiles - 1` as well

2023-03-17 10:27 UTC, NinaDang97 approved these changes
Remember to decrease `totalFiles` after deletion, and we are good to go!

2023-03-17 10:28 UTC, NinaDang97 commented on packages/frontend/src/components/Files/StaticFileCard.tsx
> +const NodeTypes = {
NodeTypes is duplicated in File.tsx, can export

2023-03-17 11:00 UTC, merged

2023-03-20 06:44 UTC, NinaDang97 commented on packages/frontend/src/components/Files/CategoryFiles.tsx
> +        `http://localhost:3002/api/alfresco/files?category=${getRouterName(categoryName)}&page=${page}`,
Could you remove localhost?