Feat/RTENU-191 toolbar unit test
finnishtransportagency/ratatiedot-extranet pull request #209
Opened 2023-04-04 16:30 UTC by NinaDang97

- Move `getCategoryRouteName` away from helper file as Jest failed to run
- Unit test for SlateToolbar and SlateInputField
- Cypress test for SlateToolbar and SlateInputField

2023-04-05 05:33 UTC, mehtis requested changes

2023-04-05 05:33 UTC, mehtis commented on packages/frontend/src/components/Editor/SlateToolbar.tsx
> +      <ToolbarPaperWrapper elevation={2} aria-label="toolbar">
These aria-labels should be translated texts. Maybe you can as @noravux for help?

2023-04-06 09:39 UTC, mehtis approved these changes

2023-04-06 09:47 UTC, noravux approved these changes

2023-04-06 09:52 UTC, merged