Bugfix/postgresql lambda
finnishtransportagency/ratatiedot-extranet pull request #96
Opened 2022-12-13 14:13 UTC by saneDG

Fix two lambdas by nest database queries in try-catch block.

2022-12-14 05:26 UTC, mehtis requested changes

2022-12-14 05:26 UTC, mehtis commented on packages/server/lambdas/list-users.ts
> -    log.info(user, 'Listing users');
Return this logging (so it won't be forgotten that easily when real things start to happen.

2022-12-14 08:02 UTC, NinaDang97 commented on packages/server/lambdas/create-user.ts
> +    const cretedUser = await database.user.create({
typo `createdUser`?

2022-12-19 10:20 UTC, mehtis approved these changes

2022-12-19 10:21 UTC, merged